window.CYBER_DEALS = [
  {
    "source": "All Nutrition",
    "category": "whey",
    "title": "Mutant Whey Protein 5 Lb",
    "price": 61590,
    "original_price": 76990,
    "discount_pct": 20.0,
    "weight_grams": 2268.0,
    "net_protein_grams": 1655.6,
    "cost_per_gram_clp": 37.2,
    "permalink": "https://allnutrition.cl/products/100-whey-protein-5lb-mutant"
  },
  {
    "source": "Supletech",
    "category": "isolate",
    "title": "iso HD whey protein isolate 5 lbs - Bpi Sports",
    "price": 89990,
    "original_price": null,
    "discount_pct": 0.0,
    "weight_grams": 2268.0,
    "net_protein_grams": 1950.5,
    "cost_per_gram_clp": 46.14,
    "permalink": "https://supletech.cl/iso-hd-bpi/p"
  },
  {
    "source": "All Nutrition",
    "category": "whey",
    "title": "Whey Gold, Ultimate Nutrition Whey Protein 5 Lb",
    "price": 76990,
    "original_price": 77990,
    "discount_pct": 1.3,
    "weight_grams": 2268.0,
    "net_protein_grams": 1655.6,
    "cost_per_gram_clp": 46.5,
    "permalink": "https://allnutrition.cl/products/whey-gold-5-lb-ultimate-nutrition"
  },
  {
    "source": "All Nutrition",
    "category": "whey",
    "title": "TROPHIX 5 LB, SYNTRAX",
    "price": 79990,
    "original_price": null,
    "discount_pct": 0.0,
    "weight_grams": 2268.0,
    "net_protein_grams": 1655.6,
    "cost_per_gram_clp": 48.31,
    "permalink": "https://allnutrition.cl/products/trophix-5-lb-syntrax"
  },
  {
    "source": "Supletech",
    "category": "isolate",
    "title": "Animal Whey isolate 4lbs - Animal Vainilla",
    "price": 76990,
    "original_price": 89990,
    "discount_pct": 14.4,
    "weight_grams": 1814.4,
    "net_protein_grams": 1560.4,
    "cost_per_gram_clp": 49.34,
    "permalink": "https://supletech.cl/animal-whey-isolate-4lbs/p"
  },
  {
    "source": "All Nutrition",
    "category": "whey",
    "title": "Impact, Myprotein Whey Protein 2.5 kg",
    "price": 90990,
    "original_price": 92990,
    "discount_pct": 2.2,
    "weight_grams": 2500.0,
    "net_protein_grams": 1825.0,
    "cost_per_gram_clp": 49.86,
    "permalink": "https://allnutrition.cl/products/impact-whey-protein-2-5-kg-myprotein"
  },
  {
    "source": "All Nutrition",
    "category": "isolate",
    "title": "ISO Surge, Mutant Isolate Protein 5 Lb",
    "price": 97740,
    "original_price": 114990,
    "discount_pct": 15.0,
    "weight_grams": 2268.0,
    "net_protein_grams": 1950.5,
    "cost_per_gram_clp": 50.11,
    "permalink": "https://allnutrition.cl/products/iso-surge-5-lb-mutant"
  },
  {
    "source": "All Nutrition",
    "category": "whey",
    "title": "Syntha 6, Whey protein (5 Lb) - Original",
    "price": 82990,
    "original_price": 89990,
    "discount_pct": 7.8,
    "weight_grams": 2268.0,
    "net_protein_grams": 1655.6,
    "cost_per_gram_clp": 50.13,
    "permalink": "https://allnutrition.cl/products/syntha-6-5-lb"
  },
  {
    "source": "Supletech",
    "category": "whey",
    "title": "Animal Whey 4lbs - Animal Chocolate",
    "price": 68990,
    "original_price": 79990,
    "discount_pct": 13.8,
    "weight_grams": 1814.4,
    "net_protein_grams": 1324.5,
    "cost_per_gram_clp": 52.09,
    "permalink": "https://supletech.cl/animal-whey-4lbs/p"
  },
  {
    "source": "Supletech",
    "category": "whey",
    "title": "100% Whey 5 lbs - Nutrex Chocolate",
    "price": 86990,
    "original_price": 90990,
    "discount_pct": 4.4,
    "weight_grams": 2268.0,
    "net_protein_grams": 1655.6,
    "cost_per_gram_clp": 52.54,
    "permalink": "https://supletech.cl/100-whey-5-lbs-nutrex/p"
  },
  {
    "source": "Supletech",
    "category": "whey",
    "title": "Whey Protein 2lbs - Ghost Cereal Milk",
    "price": 34990,
    "original_price": 58990,
    "discount_pct": 40.7,
    "weight_grams": 907.2,
    "net_protein_grams": 662.3,
    "cost_per_gram_clp": 52.83,
    "permalink": "https://supletech.cl/ghost-whey-2lbs/p"
  },
  {
    "source": "Winkler Nutrition",
    "category": "casein",
    "title": "Caseína Micellar Casein 1 kg – 33 servicios",
    "price": 42990,
    "original_price": null,
    "discount_pct": 0.0,
    "weight_grams": 1000.0,
    "net_protein_grams": 760.0,
    "cost_per_gram_clp": 56.57,
    "permalink": "https://winklernutrition.cl/products/caseina-micellar-casein-1-kg-33-servicios"
  },
  {
    "source": "All Nutrition",
    "category": "whey",
    "title": "ProStar, Ultimate Nutrition Whey Protein 5 Lb",
    "price": 94490,
    "original_price": 104990,
    "discount_pct": 10.0,
    "weight_grams": 2268.0,
    "net_protein_grams": 1655.6,
    "cost_per_gram_clp": 57.07,
    "permalink": "https://allnutrition.cl/products/prostar-whey-protein-5-lb"
  },
  {
    "source": "All Nutrition",
    "category": "whey",
    "title": "Gold Standard, Optimum Nutrition Whey Protein 5 Lb",
    "price": 97190,
    "original_price": 107990,
    "discount_pct": 10.0,
    "weight_grams": 2268.0,
    "net_protein_grams": 1655.6,
    "cost_per_gram_clp": 58.7,
    "permalink": "https://allnutrition.cl/products/100-whey-protein-5lb-gold-standard-optimum-nutrition"
  },
  {
    "source": "All Nutrition",
    "category": "casein",
    "title": "MICELLAR CREME 2 LB, SYNTRAX",
    "price": 41990,
    "original_price": null,
    "discount_pct": 0.0,
    "weight_grams": 907.2,
    "net_protein_grams": 689.5,
    "cost_per_gram_clp": 60.9,
    "permalink": "https://allnutrition.cl/products/micellar-creme-2-lb-milkshake-syntrax"
  }
];
